name: Check linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, holoscan-sdk-lws2]

permissions:
  contents: read

env:
  HOLOSCAN_CLI_VERSION: holoscan-cli==4.3.0a26390596878
  HOLOSCAN_CLI_INSTALL_EXTRA_FLAGS: "--index-url https://test.pypi.org/simple/"

jobs:
  check-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install holoscan-cli
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            --index-url https://test.pypi.org/simple/ \
            holoscan-cli==4.3.0a26390596878

      - name: Install Dependencies
        run: ./holohub lint --install-dependencies

      - name: Run linter
        run: ./holohub lint
